apiVersion: v1
kind: Service
metadata:
  namespace: device-service
  labels:
    app: device-service
  name: device-service
spec:
  ports:
  
    - protocol: TCP
      port: 3999
      targetPort: 3999
   
   
  selector:
    app: device-service
  type: ClusterIP
